# Configuración de GitHub Pages para Legal Cases API
title: "Legal Cases API"
description: "API REST pública para casos legales - Práctica y desarrollo"

# Configuración del sitio
url: "https://tu-usuario.github.io"
baseurl: "/api-exp"

# Plugins para GitHub Pages
plugins:
  - jekyll-sitemap

# Configuración adicional
markdown: kramdown
highlighter: rouge

# Incluir archivos JSON en el sitio
include:
  - api.json
  - examples/

# Configuración de CORS (mediante headers)
headers:
  api.json:
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Methods: "GET"
    Access-Control-Allow-Headers: "Content-Type"
    Content-Type: "application/json"
